#pragma once

#include <map>
#include "common.hpp"

enum class PLANT_ID {
    PLANT_1,
    PLANT_1_PURPLE,
    PLANT_1_YELLOW,
    PLANT_2,
    PLANT_2_PURPLE,
    PLANT_2_CYAN,
    PLANT_3,
    PLANT_3_BLUE
};

enum class PLANT_TYPE {
    PROJECTILE,
    HEAL,
    POISON,
    SLOW
};

struct stats {
    int health;
    int damage;
    int range;
    int cooldown;
    PLANT_TYPE type;
    stats(int health, int damage, int range, int cooldown, PLANT_TYPE type) : health(health), damage(damage), range(range), cooldown(cooldown), type(type) {}
};

struct animation {
    const TEXTURE_ASSET_ID* textures;
    int size;
    int duration;
    animation(const TEXTURE_ASSET_ID* textures, int size, int duration) : textures(textures), size(size), duration(duration) {}
};

struct animation_state {
    animation idle;
    animation attack;
    animation_state(animation idle, animation attack) : idle(idle), attack(attack) {}
};

const TEXTURE_ASSET_ID PLANT_1_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_1_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_1_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_1_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_1_IDLE_4
};
const TEXTURE_ASSET_ID PLANT_1_PURPLE_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_IDLE_4
};
const TEXTURE_ASSET_ID PLANT_1_YELLOW_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_IDLE_4
};
const TEXTURE_ASSET_ID PLANT_2_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_2_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_2_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_2_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_2_IDLE_4
};
const TEXTURE_ASSET_ID PLANT_2_PURPLE_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_IDLE_4
};
const TEXTURE_ASSET_ID PLANT_2_CYAN_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_2_CYAN_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_IDLE_4
};
const TEXTURE_ASSET_ID PLANT_3_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_3_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_3_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_3_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_3_IDLE_4
};
const TEXTURE_ASSET_ID PLANT_3_BLUE_IDLE_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_3_BLUE_IDLE_1,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_IDLE_2,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_IDLE_3,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_IDLE_4
};

const TEXTURE_ASSET_ID PLANT_1_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_1_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_1_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_1_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_1_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_1_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_1_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_1_ATTACK_7
};
const TEXTURE_ASSET_ID PLANT_1_PURPLE_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_1_PURPLE_ATTACK_7
};
const TEXTURE_ASSET_ID PLANT_1_YELLOW_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_1_YELLOW_ATTACK_7
};
const TEXTURE_ASSET_ID PLANT_2_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_2_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_2_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_2_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_2_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_2_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_2_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_2_ATTACK_7
};
const TEXTURE_ASSET_ID PLANT_2_PURPLE_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_2_PURPLE_ATTACK_7
};
const TEXTURE_ASSET_ID PLANT_2_CYAN_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_2_CYAN_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_2_CYAN_ATTACK_7
};
const TEXTURE_ASSET_ID PLANT_3_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_3_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_3_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_3_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_3_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_3_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_3_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_3_ATTACK_7
};
const TEXTURE_ASSET_ID PLANT_3_BLUE_ATTACK_ANIM_TEXTURES[] = {
    TEXTURE_ASSET_ID::PLANT_3_BLUE_ATTACK_1,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_ATTACK_2,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_ATTACK_3,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_ATTACK_4,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_ATTACK_5,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_ATTACK_6,
    TEXTURE_ASSET_ID::PLANT_3_BLUE_ATTACK_7
};

const int PLANT_1_IDLE_ANIM_SIZE = sizeof(PLANT_1_IDLE_ANIM_TEXTURES) / sizeof(PLANT_1_IDLE_ANIM_TEXTURES[0]);
const int PLANT_1_PURPLE_IDLE_ANIM_SIZE = sizeof(PLANT_1_PURPLE_IDLE_ANIM_TEXTURES) / sizeof(PLANT_1_PURPLE_IDLE_ANIM_TEXTURES[0]);
const int PLANT_1_YELLOW_IDLE_ANIM_SIZE = sizeof(PLANT_1_YELLOW_IDLE_ANIM_TEXTURES) / sizeof(PLANT_1_YELLOW_IDLE_ANIM_TEXTURES[0]);
const int PLANT_2_IDLE_ANIM_SIZE = sizeof(PLANT_2_IDLE_ANIM_TEXTURES) / sizeof(PLANT_2_IDLE_ANIM_TEXTURES[0]);
const int PLANT_2_PURPLE_IDLE_ANIM_SIZE = sizeof(PLANT_2_PURPLE_IDLE_ANIM_TEXTURES) / sizeof(PLANT_2_PURPLE_IDLE_ANIM_TEXTURES[0]);
const int PLANT_2_CYAN_IDLE_ANIM_SIZE = sizeof(PLANT_2_CYAN_IDLE_ANIM_TEXTURES) / sizeof(PLANT_2_CYAN_IDLE_ANIM_TEXTURES[0]);
const int PLANT_3_IDLE_ANIM_SIZE = sizeof(PLANT_3_IDLE_ANIM_TEXTURES) / sizeof(PLANT_3_IDLE_ANIM_TEXTURES[0]);
const int PLANT_3_BLUE_IDLE_ANIM_SIZE = sizeof(PLANT_3_BLUE_IDLE_ANIM_TEXTURES) / sizeof(PLANT_3_BLUE_IDLE_ANIM_TEXTURES[0]);

const int PLANT_1_ATTACK_ANIM_SIZE = sizeof(PLANT_1_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_1_ATTACK_ANIM_TEXTURES[0]);
const int PLANT_1_PURPLE_ATTACK_ANIM_SIZE = sizeof(PLANT_1_PURPLE_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_1_PURPLE_ATTACK_ANIM_TEXTURES[0]);
const int PLANT_1_YELLOW_ATTACK_ANIM_SIZE = sizeof(PLANT_1_YELLOW_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_1_YELLOW_ATTACK_ANIM_TEXTURES[0]);
const int PLANT_2_ATTACK_ANIM_SIZE = sizeof(PLANT_2_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_2_ATTACK_ANIM_TEXTURES[0]);
const int PLANT_2_PURPLE_ATTACK_ANIM_SIZE = sizeof(PLANT_2_PURPLE_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_2_PURPLE_ATTACK_ANIM_TEXTURES[0]);
const int PLANT_2_CYAN_ATTACK_ANIM_SIZE = sizeof(PLANT_2_CYAN_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_2_CYAN_ATTACK_ANIM_TEXTURES[0]);
const int PLANT_3_ATTACK_ANIM_SIZE = sizeof(PLANT_3_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_3_ATTACK_ANIM_TEXTURES[0]);
const int PLANT_3_BLUE_ATTACK_ANIM_SIZE = sizeof(PLANT_3_BLUE_ATTACK_ANIM_TEXTURES) / sizeof(PLANT_3_BLUE_ATTACK_ANIM_TEXTURES[0]);

const int PLANT_1_IDLE_ANIM_DURATION = 2000;
const int PLANT_1_PURPLE_IDLE_ANIM_DURATION = 2000;
const int PLANT_1_YELLOW_IDLE_ANIM_DURATION = 2000;
const int PLANT_2_IDLE_ANIM_DURATION = 2000;
const int PLANT_2_PURPLE_IDLE_ANIM_DURATION = 2000;
const int PLANT_2_CYAN_IDLE_ANIM_DURATION = 2000;
const int PLANT_3_IDLE_ANIM_DURATION = 2000;
const int PLANT_3_BLUE_IDLE_ANIM_DURATION = 2000;

const int PLANT_1_ATTACK_ANIM_DURATION = 4000;
const int PLANT_1_PURPLE_ATTACK_ANIM_DURATION = 4000;
const int PLANT_1_YELLOW_ATTACK_ANIM_DURATION = 4000;
const int PLANT_2_ATTACK_ANIM_DURATION = 2000;
const int PLANT_2_PURPLE_ATTACK_ANIM_DURATION = 1000;
const int PLANT_2_CYAN_ATTACK_ANIM_DURATION = 1000;
const int PLANT_3_ATTACK_ANIM_DURATION = 1000;
const int PLANT_3_BLUE_ATTACK_ANIM_DURATION = 1000;

const animation PLANT_1_IDLE_ANIM(PLANT_1_IDLE_ANIM_TEXTURES, PLANT_1_IDLE_ANIM_SIZE, PLANT_1_IDLE_ANIM_DURATION);
const animation PLANT_1_PURPLE_IDLE_ANIM(PLANT_1_PURPLE_IDLE_ANIM_TEXTURES, PLANT_1_PURPLE_IDLE_ANIM_SIZE, PLANT_1_PURPLE_IDLE_ANIM_DURATION);
const animation PLANT_1_YELLOW_IDLE_ANIM(PLANT_1_YELLOW_IDLE_ANIM_TEXTURES, PLANT_1_YELLOW_IDLE_ANIM_SIZE, PLANT_1_YELLOW_IDLE_ANIM_DURATION);
const animation PLANT_2_IDLE_ANIM(PLANT_2_IDLE_ANIM_TEXTURES, PLANT_2_IDLE_ANIM_SIZE, PLANT_2_IDLE_ANIM_DURATION);
const animation PLANT_2_PURPLE_IDLE_ANIM(PLANT_2_PURPLE_IDLE_ANIM_TEXTURES, PLANT_2_PURPLE_IDLE_ANIM_SIZE, PLANT_2_PURPLE_IDLE_ANIM_DURATION);
const animation PLANT_2_CYAN_IDLE_ANIM(PLANT_2_CYAN_IDLE_ANIM_TEXTURES, PLANT_2_CYAN_IDLE_ANIM_SIZE, PLANT_2_CYAN_IDLE_ANIM_DURATION);
const animation PLANT_3_IDLE_ANIM(PLANT_3_IDLE_ANIM_TEXTURES, PLANT_3_IDLE_ANIM_SIZE, PLANT_3_IDLE_ANIM_DURATION);
const animation PLANT_3_BLUE_IDLE_ANIM(PLANT_3_BLUE_IDLE_ANIM_TEXTURES, PLANT_3_BLUE_IDLE_ANIM_SIZE, PLANT_3_BLUE_IDLE_ANIM_DURATION);

const animation PLANT_1_ATTACK_ANIM(PLANT_1_ATTACK_ANIM_TEXTURES, PLANT_1_ATTACK_ANIM_SIZE, PLANT_1_ATTACK_ANIM_DURATION);
const animation PLANT_1_PURPLE_ATTACK_ANIM(PLANT_1_PURPLE_ATTACK_ANIM_TEXTURES, PLANT_1_PURPLE_ATTACK_ANIM_SIZE, PLANT_1_PURPLE_ATTACK_ANIM_DURATION);
const animation PLANT_1_YELLOW_ATTACK_ANIM(PLANT_1_YELLOW_ATTACK_ANIM_TEXTURES, PLANT_1_YELLOW_ATTACK_ANIM_SIZE, PLANT_1_YELLOW_ATTACK_ANIM_DURATION);
const animation PLANT_2_ATTACK_ANIM(PLANT_2_ATTACK_ANIM_TEXTURES, PLANT_2_ATTACK_ANIM_SIZE, PLANT_2_ATTACK_ANIM_DURATION);
const animation PLANT_2_PURPLE_ATTACK_ANIM(PLANT_2_PURPLE_ATTACK_ANIM_TEXTURES, PLANT_2_PURPLE_ATTACK_ANIM_SIZE, PLANT_2_PURPLE_ATTACK_ANIM_DURATION);
const animation PLANT_2_CYAN_ATTACK_ANIM(PLANT_2_CYAN_ATTACK_ANIM_TEXTURES, PLANT_2_CYAN_ATTACK_ANIM_SIZE, PLANT_2_CYAN_ATTACK_ANIM_DURATION);
const animation PLANT_3_ATTACK_ANIM(PLANT_3_ATTACK_ANIM_TEXTURES, PLANT_3_ATTACK_ANIM_SIZE, PLANT_3_ATTACK_ANIM_DURATION);
const animation PLANT_3_BLUE_ATTACK_ANIM(PLANT_3_BLUE_ATTACK_ANIM_TEXTURES, PLANT_3_BLUE_ATTACK_ANIM_SIZE, PLANT_3_BLUE_ATTACK_ANIM_DURATION);

const int PLANT_1_HEALTH = 15;
const int PLANT_1_PURPLE_HEALTH = 15;
const int PLANT_1_YELLOW_HEALTH = 15;
const int PLANT_2_HEALTH = 15;
const int PLANT_2_PURPLE_HEALTH = 15;
const int PLANT_2_CYAN_HEALTH = 15;
const int PLANT_3_HEALTH = 15;
const int PLANT_3_BLUE_HEALTH = 15;

const int PLANT_1_DAMAGE = 10;
const int PLANT_1_PURPLE_DAMAGE = 10;
const int PLANT_1_YELLOW_DAMAGE = 10;
const int PLANT_2_DAMAGE = 10;
const int PLANT_2_PURPLE_DAMAGE = 5;
const int PLANT_2_CYAN_DAMAGE = 50;
const int PLANT_3_DAMAGE = 10;
const int PLANT_3_BLUE_DAMAGE = 10;

const int PLANT_1_RANGE = GRID_CELL_WIDTH_PX * 20;
const int PLANT_1_PURPLE_RANGE = GRID_CELL_WIDTH_PX * 20;
const int PLANT_1_YELLOW_RANGE = GRID_CELL_WIDTH_PX * 20;
const int PLANT_2_RANGE = GRID_CELL_WIDTH_PX * 10;
const int PLANT_2_PURPLE_RANGE = GRID_CELL_WIDTH_PX * 5;
const int PLANT_2_CYAN_RANGE = GRID_CELL_WIDTH_PX * 5;
const int PLANT_3_RANGE = GRID_CELL_WIDTH_PX * 5;
const int PLANT_3_BLUE_RANGE = GRID_CELL_WIDTH_PX * 5;

const int PLANT_1_COOLDOWN = PLANT_1_ATTACK_ANIM_DURATION;
const int PLANT_1_PURPLE_COOLDOWN = PLANT_1_PURPLE_ATTACK_ANIM_DURATION;
const int PLANT_1_YELLOW_COOLDOWN = PLANT_1_YELLOW_ATTACK_ANIM_DURATION;
const int PLANT_2_COOLDOWN = PLANT_2_ATTACK_ANIM_DURATION;
const int PLANT_2_PURPLE_COOLDOWN = 500;
const int PLANT_2_CYAN_COOLDOWN = 500;
const int PLANT_3_COOLDOWN = PLANT_3_ATTACK_ANIM_DURATION;
const int PLANT_3_BLUE_COOLDOWN = PLANT_3_BLUE_ATTACK_ANIM_DURATION;

const std::map<PLANT_ID, animation_state>
PLANT_ANIMATION_MAP = {
    {PLANT_ID::PLANT_1, animation_state(PLANT_1_IDLE_ANIM, PLANT_1_ATTACK_ANIM)},
    {PLANT_ID::PLANT_1_PURPLE, animation_state(PLANT_1_PURPLE_IDLE_ANIM, PLANT_1_PURPLE_ATTACK_ANIM)},
    {PLANT_ID::PLANT_1_YELLOW, animation_state(PLANT_1_YELLOW_IDLE_ANIM, PLANT_1_YELLOW_ATTACK_ANIM)},
    {PLANT_ID::PLANT_2, animation_state(PLANT_2_IDLE_ANIM, PLANT_2_ATTACK_ANIM)},
    {PLANT_ID::PLANT_2_PURPLE, animation_state(PLANT_2_PURPLE_IDLE_ANIM, PLANT_2_PURPLE_ATTACK_ANIM)},
    {PLANT_ID::PLANT_2_CYAN, animation_state(PLANT_2_CYAN_IDLE_ANIM, PLANT_2_CYAN_ATTACK_ANIM)},
    {PLANT_ID::PLANT_3, animation_state(PLANT_3_IDLE_ANIM, PLANT_3_ATTACK_ANIM)},
    {PLANT_ID::PLANT_3_BLUE, animation_state(PLANT_3_BLUE_IDLE_ANIM, PLANT_3_BLUE_ATTACK_ANIM)}
};

const std::map<PLANT_ID, stats>
PLANT_STATS_MAP = {
    {PLANT_ID::PLANT_1, stats(PLANT_1_HEALTH, PLANT_1_DAMAGE, PLANT_1_RANGE, PLANT_1_COOLDOWN, PLANT_TYPE::PROJECTILE)},
    {PLANT_ID::PLANT_1_PURPLE, stats(PLANT_1_PURPLE_HEALTH, PLANT_1_PURPLE_DAMAGE, PLANT_1_PURPLE_RANGE, PLANT_1_PURPLE_COOLDOWN, PLANT_TYPE::PROJECTILE)},
    {PLANT_ID::PLANT_1_YELLOW, stats(PLANT_1_YELLOW_HEALTH, PLANT_1_YELLOW_DAMAGE, PLANT_1_YELLOW_RANGE, PLANT_1_YELLOW_COOLDOWN, PLANT_TYPE::PROJECTILE)},
    {PLANT_ID::PLANT_2, stats(PLANT_2_HEALTH, PLANT_2_DAMAGE, PLANT_2_RANGE, PLANT_2_COOLDOWN, PLANT_TYPE::PROJECTILE)},
    {PLANT_ID::PLANT_2_PURPLE, stats(PLANT_2_PURPLE_HEALTH, PLANT_2_PURPLE_DAMAGE, PLANT_2_PURPLE_RANGE, PLANT_2_PURPLE_COOLDOWN, PLANT_TYPE::POISON)},
    {PLANT_ID::PLANT_2_CYAN, stats(PLANT_2_CYAN_HEALTH, PLANT_2_CYAN_DAMAGE, PLANT_2_CYAN_RANGE, PLANT_2_CYAN_COOLDOWN, PLANT_TYPE::SLOW)},
    {PLANT_ID::PLANT_3, stats(PLANT_3_HEALTH, PLANT_3_DAMAGE, PLANT_3_RANGE, PLANT_3_COOLDOWN, PLANT_TYPE::PROJECTILE)},
    {PLANT_ID::PLANT_3_BLUE, stats(PLANT_3_BLUE_HEALTH, PLANT_3_BLUE_DAMAGE, PLANT_3_BLUE_RANGE, PLANT_3_BLUE_COOLDOWN, PLANT_TYPE::PROJECTILE)}
};

const std::map<PLANT_ID, TEXTURE_ASSET_ID>
PLANT_PROJECTILE_MAP = {
    {PLANT_ID::PLANT_1, TEXTURE_ASSET_ID::PROJECTILE},
    {PLANT_ID::PLANT_1_PURPLE, TEXTURE_ASSET_ID::PROJECTILE_ORANGE},
    {PLANT_ID::PLANT_1_YELLOW, TEXTURE_ASSET_ID::PROJECTILE_RED}
};
